### ISSUE TITLE
Concurrent registration without queues

### ISSUE THREAD

**Issue by christopher-dG** [JuliaRegistries/Registrator.jl#159]
As mentioned in #135. 
Currently we use a queue to handle one registration at a time, always operating on a registry in the same directory. But to minimize waiting, it would be better to clone the registry in a new temp subdirectory for each request. 
Obviously we we would need to set some concurrency limit to avoid running out of disk space.

**Comment by nkottary** [comment]
I don't think we should get rid of the queue because without it there is no way to stop or restart the WebUI without dropping some user requests. I know this isn't a problem now because `register()` is super fast and it is easy for us to tell when Registrator is idle by looking at the logs (which still isn't the best way). Once we have Registrator doing or waiting for CI though we will need the queue.

Regarding doing parallel registrations, the thing I had in mind while working on #135 was to have multiple `regservice` processes running and we load balance on them via ZMQ router-dealer.

**Comment by christopher-dG** [comment]
> Once we have Registrator doing or waiting for CI though we will need the queue.

It's unclear to me why. Could you elaborate?

> multiple regservice processes running and we load balance

Registrator handles a handful of requests per hour, I doubt that the rate will increase past a few per minute even years from now. With that in mind, I don't think the added complexity is worth it.

**Comment by nkottary** [comment]
Then why have you opened this issue? What is the need for concurrency right now?   I was suggesting the simplest way to achieve it if needed not saying that it is necessary. Isn't adding multiple registry caches as you mentioned above also an added complexity to the already complex register function?

There is no significant wait time with #135 AFAICT except for the first register which triggers a clone. This was a 504 gateway timeout earlier in WebUI.

> It's unclear to me why. Could you elaborate?

How do you ensure that you're not denying a user's request when you restart the server after applying a patch on Registrator?

**Comment by christopher-dG** [comment]
This alternate approach is a workaround for the requirement of polling logic on the web frontend. I don't think that the proposed solution is more complex than the existing one. 

I think we're perhaps worrying about hypothetical downtime too much, when that isn't really a concern for the server itself but rather for methods independent of the actual code, e.g. blue-green deployment. But I concede that a) It would be a shame to waste the significant existing work and b) I am not someone working at Julia Computing that has to deal with this deployment.

**Comment by StefanKarpinski** [comment]
In my experience, any time you have two services that are feeding thing from one to the other, you end up implementing something that's a queuing system whether you acknowledge it or not. Using ZMQ up front seems better than accidentally creating a queuing system that's less well designed and tested. ZMQ has the immediate benefit of doing a good job of not losing requests when one or both sides of the queue are restarted. If we want to change the comment listener so that it can figure out when it has missed a comment while it was down, we can do that as well completely independently and then we'll have an even more reliable system.

> Registrator handles a handful of requests per hour, I doubt that the rate will increase past a few per minute even years from now.

It will probably only ever be a few per hour but we may do much more substantial CI, which means we'll want to handle more than one registration request concurrently.

**Comment by christopher-dG** [comment]
After thinking about it some more I think my concerns are misdirected. I'm fine with queueing, and the polling is still not ideal to me but it's alright since alternatives could prove difficult.

I still do think though that the code restructuring in order to do what is essentially code reloading adds more complexity than is needed, and maintaining uptime should not be the responsibility of Registrator, but rather of good deployment practices. I wish I had thought about this more when #131 was first opened so I could have chimed in.

At the end of the day though, this is still Julia Computing's project so whatever is easiest to deploy and maintain for you/them makes sense.

**Comment by christopher-dG** [comment]
I'll go ahead and close this, since my concern is not really with the code. I'll yell into the void about deployment practices somewhere else if I feel like it :slightly_smiling_face:

**Comment by StefanKarpinski** [comment]
Just to put it down in writing somewhere public and non-transient, I'd ideally like to get registrator to the point where it's continuously deployed—in the sense that whatever is merged to master is automatically deployed immediately to the public running version of registrator, ideally as part of the merge process. Obviously, this requires a really reliable test suite, which we're pretty far away from, but once we have that something like bors could do the following:

1. run the test suite
2. deploy to a staging server
3. do a test registration in staging
4. deploy to the production server
5. push newly merged and deployed master

If any of the steps fails, it would stop the merge to master, leaving the PR open and reporting the failure as a CI status. We have a way to go to that that's where I'd like to get to.
