### ISSUE TITLE
A concern for scientific projects

### ISSUE THREAD

**Issue by Datseris** [JuliaRegistries/Registrator.jl#49]
(pasting this from Slack)

The "old way", whereby tagging a release on GitHub meant also tagging a release in METADATA is very powerful and I hate to see it go. But for the sake of change and improvement old ways have to be forgotten. There is something from the old way that should not be forgotten though: that there is an automatic link between package release and GitHub release.

The main reason: scientific repositories that use e.g. ZENODO to have a DOI for their code base. ZENODO nicely integrates with GitHub and stores the data in a way that is directly tied with the GitHub release.

I fear that with the new system of "making a pull request" a bad thing may happen: simply forgetting to tag a GitHub release for every "Package release". Especially in the case of many subsequent bugfix releases I hope you can see this as a realistic scenario.

**Comment by jpsamaroo** [comment]
If we can have registry release tagging as an optional feature to be enabled (say during activation of the Registrator app on the Github repository of interest, or via some sort of a `config()` call to the registrator bot), that would indeed mitigate people occasionally forgetting to register new tags manually.

**Comment by Datseris** [comment]
@StefanKarpinski I am tagging you here after a discussion with @pfitzseb  on Slack. Seb mentioned you had the idea of having a second minor bot that does the "GitHub" tagging (and thus has write permission).

I just want to say that I very much support this and in general for me it is worth it to give write permission in exchange of automatic GitHub tagging.

**Comment by StefanKarpinski** [comment]
Yes, I think we should definitely have such a bot. If someone wants to work on it, it would be a good separate, self-contained project. Much of the code already exists in this repo because Registrator did previously do tagging automatically but the feedback was that some people did not want to give the bot write access to their repos, hence the idea for a separate bot that people could opt into using that just creates tags/releases after package versions have been registered.

**Comment by tpoisot** [comment]
I like the new system -- in the previous iteration, an issue with the tag meant that zenodo would create DOIs for things that were not merged (or that we edited the content after the fact, so the DOI pointed to something different from the release).

I would be happy to see a bot that either tags automatically, or sends a reminder to tag after the PR is merged.

**Comment by StefanKarpinski** [comment]
The problem of needing to retag things was very real and quite problematic since git tags and GitHub releases are not meant to be mutable. As we add more checks on the registration process to make sure that new versions pass their own tests and actually work with other packages that they claim to, this problem would get much worse. The new process avoids this and only lacks automatic tagging, which can be done with a simple bot after the fact.

**Comment by christopher-dG** [comment]
Hello: https://github.com/christopher-dG/tag-bot

**Comment by Datseris** [comment]
Amazing, you guys rock!

**Comment by DilumAluthge** [comment]
Now that TagBot is up and running, can we close this issue?

cc: @Datseris
